export default {
  'get-started': 'Get Started',
  quickstart: 'Quickstarts',
  features: 'Features',
  pricing: 'Pricing',
  academy: '🎓 Academy (Integrator)',
  blocksSeparator: { type: 'separator', title: 'Building Blocks' },
  clients: 'Clients',
  connections: 'Connections',
  social: 'Social Login',
  passwordless: 'Passwordless',
  'hosted-login': 'Hosted Login UI',
  'login-experience': 'Login Experience',
  apis: 'APIs',
  protocolSeparator: { type: 'separator', title: 'Protocol' },
  'oauth-flows': 'OAuth 2.0 Flows',
  oidc: 'OpenID Connect',
  'validate-access-tokens': 'Validate Access Tokens',
  usersSeparator: { type: 'separator', title: 'Users & Sessions' },
  signup: 'Signup',
  'change-email': 'Change Email',
  'email-sending': 'Email Sending',
  'phone-verification': 'Phone Verification',
  'team-invitations': 'Team Invitations',
  'suspend-users': 'Suspend Users',
  mfa: 'Two-Step Verification',
  logs: 'Logs',
  errors: 'Error Codes',
  advancedSeparator: { type: 'separator', title: 'Advanced' },
  'login-flows': 'Login Flows',
  extensibility: 'Extensibility',
  'custom-domain': 'Custom Domain',
  integrations: 'Integrations',
  learnSeparator: { type: 'separator', title: 'Learn & Compare' },
  'what-is-a-multi-tenant-identity-server':
    'What is a multi-tenant identity server?',
  compare: 'Faable Auth vs Auth0, Clerk & Keycloak',
  'compare-aws-cognito': 'vs AWS Cognito',
  'compare-firebase-auth': 'vs Firebase Authentication',
  'compare-supabase-auth': 'vs Supabase Auth',
  'compare-authelia': 'vs Authelia',
  guides: 'Migration Guides'
}
