export default {
  "get-started": "Get Started",
  quickstart: "Quickstarts",
  "what-is-a-multi-tenant-identity-server":
    "What is a multi-tenant identity server?",
  compare: "Faable Auth vs Auth0, Clerk & Keycloak",
  "compare-aws-cognito": "vs AWS Cognito",
  "compare-firebase-auth": "vs Firebase Authentication",
  "compare-supabase-auth": "vs Supabase Auth",
  guides: "Migration Guides",
  academy: "🎓 Academy (Integrator)",
  signup: "Signup",
  social: "Social Login",
  "oauth-flows": "OAuth 2.0 Flows",
  oidc: "OpenID Connect",
  extensibility: "Extensibility",
  "change-email": "Change Email",
  "team-invitations": "Team Invitations",
  "suspend-users": "Suspend Users",
  apis: "APIs",
  "validate-access-tokens": "Validate Access Tokens",
  logs: "Logs",
};
